### ISSUE TITLE
Allow usage without files

### ISSUE THREAD

**Issue by kjyv** [pavelzw/slim-trees#48]
Hey, thanks for the nice presentation today :)

It would be very nice if the compressed models could also be available as bytes, not just directly saved to file. E.g. `dump_sklearn_compressed` could optionally return the bytes if no path is specified or have an overload `dumps_sklearn_compressed` to go with pickle's naming.
Likewise, the `sklearn_tree.dump()` and `lgbm_booster.dump()` methods only allow saving to file and pickle's `dumps()` method is not wrapped. Otherwise temp files would currently be necessary.

**Comment by pavelzw** [comment]
Thanks for the issue! I'll add `dumps_sklearn_compressed` and a few other methods that implement the `pickle.dumps` interface.
